/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author enzoa
 */
public class FenetreCadenas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreCadenas.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public FenetreCadenas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texte_intro = new javax.swing.JLabel();
        bt_up_1 = new javax.swing.JButton();
        bt_up_2 = new javax.swing.JButton();
        bt_up_3 = new javax.swing.JButton();
        bt_up_4 = new javax.swing.JButton();
        txt_1 = new javax.swing.JLabel();
        txt_2 = new javax.swing.JLabel();
        txt_3 = new javax.swing.JLabel();
        txt_4 = new javax.swing.JLabel();
        bt_down_1 = new javax.swing.JButton();
        bt_down_2 = new javax.swing.JButton();
        bt_down_3 = new javax.swing.JButton();
        bt_down_4 = new javax.swing.JButton();
        bt_tester = new javax.swing.JButton();
        txt_nb_exact = new javax.swing.JLabel();
        nb_nb_exact = new javax.swing.JLabel();
        txt_nb_haut = new javax.swing.JLabel();
        nb_nb_haut = new javax.swing.JLabel();
        txt_nb_bas = new javax.swing.JLabel();
        nb_nb_bas = new javax.swing.JLabel();
        txt_tentative = new javax.swing.JLabel();
        txt_score = new javax.swing.JLabel();
        bt_recommencer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texte_intro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_intro.setText("Trouvez le code en moins de 5 tentatives!");
        getContentPane().add(texte_intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 400, -1));

        bt_up_1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bt_up_1.setText("^");
        bt_up_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_up_1ActionPerformed(evt);
            }
        });
        getContentPane().add(bt_up_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        bt_up_2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bt_up_2.setText("^");
        bt_up_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_up_2ActionPerformed(evt);
            }
        });
        getContentPane().add(bt_up_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        bt_up_3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bt_up_3.setText("^");
        bt_up_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_up_3ActionPerformed(evt);
            }
        });
        getContentPane().add(bt_up_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        bt_up_4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bt_up_4.setText("^");
        bt_up_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_up_4ActionPerformed(evt);
            }
        });
        getContentPane().add(bt_up_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        txt_1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txt_1.setText("0");
        getContentPane().add(txt_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        txt_2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txt_2.setText("0");
        getContentPane().add(txt_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        txt_3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txt_3.setText("0");
        getContentPane().add(txt_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        txt_4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txt_4.setText("0");
        getContentPane().add(txt_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        bt_down_1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bt_down_1.setText("^");
        bt_down_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_down_1ActionPerformed(evt);
            }
        });
        getContentPane().add(bt_down_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        bt_down_2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bt_down_2.setText("^");
        bt_down_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_down_2ActionPerformed(evt);
            }
        });
        getContentPane().add(bt_down_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        bt_down_3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bt_down_3.setText("^");
        bt_down_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_down_3ActionPerformed(evt);
            }
        });
        getContentPane().add(bt_down_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        bt_down_4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bt_down_4.setText("^");
        bt_down_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_down_4ActionPerformed(evt);
            }
        });
        getContentPane().add(bt_down_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        bt_tester.setText("Tester");
        bt_tester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_testerActionPerformed(evt);
            }
        });
        getContentPane().add(bt_tester, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        txt_nb_exact.setText("Nombre de chiffre exact :");
        getContentPane().add(txt_nb_exact, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        nb_nb_exact.setText("0");
        getContentPane().add(nb_nb_exact, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 10, -1));

        txt_nb_haut.setText("Nombre de chiffre trop haut:");
        getContentPane().add(txt_nb_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        nb_nb_haut.setText("0");
        getContentPane().add(nb_nb_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 10, -1));

        txt_nb_bas.setText("Nombre de chiffre trop bas:");
        getContentPane().add(txt_nb_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        nb_nb_bas.setText("0");
        getContentPane().add(nb_nb_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 10, -1));

        txt_tentative.setText("Tentatives");
        getContentPane().add(txt_tentative, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        txt_score.setText("0 sur 5");
        getContentPane().add(txt_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 206, 80, 40));

        bt_recommencer.setText("Recommencer");
        bt_recommencer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_recommencerActionPerformed(evt);
            }
        });
        getContentPane().add(bt_recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_up_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_up_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_up_1ActionPerformed

    private void bt_up_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_up_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_up_2ActionPerformed

    private void bt_up_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_up_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_up_3ActionPerformed

    private void bt_up_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_up_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_up_4ActionPerformed

    private void bt_down_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_down_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_down_1ActionPerformed

    private void bt_down_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_down_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_down_2ActionPerformed

    private void bt_down_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_down_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_down_3ActionPerformed

    private void bt_down_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_down_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_down_4ActionPerformed

    private void bt_testerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_testerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_testerActionPerformed

    private void bt_recommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_recommencerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_recommencerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreCadenas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_down_1;
    private javax.swing.JButton bt_down_2;
    private javax.swing.JButton bt_down_3;
    private javax.swing.JButton bt_down_4;
    private javax.swing.JButton bt_recommencer;
    private javax.swing.JButton bt_tester;
    private javax.swing.JButton bt_up_1;
    private javax.swing.JButton bt_up_2;
    private javax.swing.JButton bt_up_3;
    private javax.swing.JButton bt_up_4;
    private javax.swing.JLabel nb_nb_bas;
    private javax.swing.JLabel nb_nb_exact;
    private javax.swing.JLabel nb_nb_haut;
    private javax.swing.JLabel texte_intro;
    private javax.swing.JLabel txt_1;
    private javax.swing.JLabel txt_2;
    private javax.swing.JLabel txt_3;
    private javax.swing.JLabel txt_4;
    private javax.swing.JLabel txt_nb_bas;
    private javax.swing.JLabel txt_nb_exact;
    private javax.swing.JLabel txt_nb_haut;
    private javax.swing.JLabel txt_score;
    private javax.swing.JLabel txt_tentative;
    // End of variables declaration//GEN-END:variables
}
