/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author enzoa
 */
public class FenetreQuiz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreQuiz.class.getName());
    
    private java.util.ArrayList<Question> listeQuestions; // Liste des questions
    private int indexQuestionCourante = 0; // Index de la question affichée
    private int score = 0; // Score du joueur

    /**
     * Creates new form FenetreQuiz
     */
    public FenetreQuiz() {
        initComponents();
        initialiserQuestions();
        afficherQuestionCourante();
    }
    private void afficherQuestionCourante() {
        if (indexQuestionCourante < listeQuestions.size()) {
            Question q = listeQuestions.get(indexQuestionCourante);
        question.setText(q.getIntitule());
        choix1.setText(q.getProposition1());
        choix2.setText(q.getProposition2());
        choix3.setText(q.getProposition3());
        choix4.setText(q.getProposition4());
        reponse.setText(""); // Efface le message de feedback
        choix1.setEnabled(true);
        choix2.setEnabled(true);
        choix3.setEnabled(true);
        choix4.setEnabled(true);
        }
    }
    private final String[] mauvaisereponse = {
    "Non",
    "Raté",
    "T'es un raté",
    "Pfffffff..",
    "ça deviens lourd là..."
    };
    private void verifierReponse(int choixUtilisateur) {
        Question q = listeQuestions.get(indexQuestionCourante);
        
        if (choixUtilisateur == q.getIndexBonneReponse()) {
            reponse.setText("Ha bah bravo.");
            score++;
        } else {
            // Génère un indice au hasard entre 0 et la longueur de mauvaisereponse
            int randomIndex = (int)(Math.random() * mauvaisereponse.length);
            reponse.setText(mauvaisereponse[randomIndex]);
        }
        // On désactive les boutons pour empêcher un 2e clic
        choix1.setEnabled(false);
        choix2.setEnabled(false);
        choix3.setEnabled(false);
        choix4.setEnabled(false);
    }
        
    private void initialiserQuestions() {
        // Exemples de questions
        listeQuestions = new java.util.ArrayList<>();
        listeQuestions.add(new Question("Quelle est la capitale de la France ?", "Rome", "Paris", "Berlin", "Madrid", 2));
        listeQuestions.add(new Question("Combien font 2 + 2 ?", "3", "5", "4", "6", 3));
        listeQuestions.add(new Question("Quel langage utilise .class ?", "Java", "Python", "C", "HTML", 1));
        listeQuestions.add(new Question("La Terre est...", "Un astéroïde", "Une étoile", "Une planète", "Une comète", 3));
        listeQuestions.add(new Question("Qui a écrit Les Misérables ?", "Victor Hugo", "Molière", "Zola", "Balzac", 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        question = new javax.swing.JLabel();
        reponse = new javax.swing.JLabel();
        btnSuivant = new javax.swing.JButton();
        choix1 = new javax.swing.JButton();
        choix2 = new javax.swing.JButton();
        choix3 = new javax.swing.JButton();
        choix4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        question.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        question.setText("Questions");
        getContentPane().add(question, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 430, 100));

        reponse.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        reponse.setText("Reponse");
        getContentPane().add(reponse, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 500, 50));

        btnSuivant.setText("Question Suivante");
        btnSuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuivantActionPerformed(evt);
            }
        });
        getContentPane().add(btnSuivant, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        choix1.setText("choix1");
        choix1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choix1ActionPerformed(evt);
            }
        });
        getContentPane().add(choix1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        choix2.setText("choix2");
        choix2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choix2ActionPerformed(evt);
            }
        });
        getContentPane().add(choix2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        choix3.setText("choix3");
        choix3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choix3ActionPerformed(evt);
            }
        });
        getContentPane().add(choix3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        choix4.setText("choix4");
        choix4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choix4ActionPerformed(evt);
            }
        });
        getContentPane().add(choix4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuivantActionPerformed
        // TODO add your handling code here:
        indexQuestionCourante++;
        if (indexQuestionCourante < listeQuestions.size()) {
            afficherQuestionCourante();
        } else {
            question.setText("T'as enfin fini!");
            if (score == listeQuestions.size()){
                vicoire v = new vicoire();
                v.setVisible(true);
                this.dispose();
            } else {
                reponse.setText("Score final : " + score + " / " + listeQuestions.size() + " Méprisable ");
            }           
            choix1.setEnabled(false);
            choix2.setEnabled(false);
            choix3.setEnabled(false);
            choix4.setEnabled(false);
            btnSuivant.setEnabled(false); // on désactive le bouton 'suivant'
        }
    }//GEN-LAST:event_btnSuivantActionPerformed

    private void choix1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choix1ActionPerformed
        // TODO add your handling code here:
        verifierReponse(1);
    }//GEN-LAST:event_choix1ActionPerformed

    private void choix2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choix2ActionPerformed
        // TODO add your handling code here:
        verifierReponse(2);
    }//GEN-LAST:event_choix2ActionPerformed

    private void choix3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choix3ActionPerformed
        // TODO add your handling code here:
        verifierReponse(3);
    }//GEN-LAST:event_choix3ActionPerformed

    private void choix4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choix4ActionPerformed
        // TODO add your handling code here:
        verifierReponse(4);
    }//GEN-LAST:event_choix4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreQuiz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuivant;
    private javax.swing.JButton choix1;
    private javax.swing.JButton choix2;
    private javax.swing.JButton choix3;
    private javax.swing.JButton choix4;
    private javax.swing.JLabel question;
    private javax.swing.JLabel reponse;
    // End of variables declaration//GEN-END:variables
}